server:
  port: 3001
spring:
  application:
    name: linux-mcp-server
  ai:
    mcp:
      server:
        name: linux-mcp-server
        version: 1.0.0
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
